#!/usr/bin/env bash
# 7 lines or less
pkill apache2
sed -i "s/80 default_serv/8080 default_serv/" /etc/nginx/sites-available/default
chmod 666 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
